/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cards;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Estudiantes
 */
public class MostrarCartas extends javax.swing.JFrame {

    /**
     * Creates new form MostrarCartas
     */
    public MostrarCartas() {
        initComponents();
    }
    
    Baraja nuevaBaraja=new Baraja();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Carta1 = new javax.swing.JLabel();
        Carta2 = new javax.swing.JLabel();
        Carta3 = new javax.swing.JLabel();
        Carta4 = new javax.swing.JLabel();
        Carta5 = new javax.swing.JLabel();
        Carta6 = new javax.swing.JLabel();
        Prueba = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        crearBaraja = new javax.swing.JMenu();
        barajar = new javax.swing.JMenu();
        repartir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Carta1.setText("Carta1");

        Carta2.setText("Carta2");

        Carta3.setText("Carta3");

        Carta4.setText("Carta4");

        Carta5.setText("Carta5");

        Carta6.setText("Carta6");

        crearBaraja.setText("Crear Baraja");
        crearBaraja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearBarajaMouseClicked(evt);
            }
        });
        jMenuBar1.add(crearBaraja);

        barajar.setText("Barajar");
        barajar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barajarMouseClicked(evt);
            }
        });
        jMenuBar1.add(barajar);

        repartir.setText("Repartir");
        repartir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                repartirMouseClicked(evt);
            }
        });
        jMenuBar1.add(repartir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Prueba)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Carta1)
                            .addComponent(Carta4))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Carta2)
                            .addComponent(Carta5))))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carta3)
                    .addComponent(Carta6))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carta3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Carta6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Carta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Carta5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Carta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Carta4)))
                .addGap(99, 99, 99)
                .addComponent(Prueba)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearBarajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBarajaMouseClicked
        nuevaBaraja.crearBaraja();
    }//GEN-LAST:event_crearBarajaMouseClicked

    private void barajarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barajarMouseClicked
        nuevaBaraja.barajar();
    }//GEN-LAST:event_barajarMouseClicked

    private void repartirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repartirMouseClicked
        nuevaBaraja.repartir(6);
        Carta1.setText(nuevaBaraja.jugador1[0].número+" de "+nuevaBaraja.jugador1[0].palo);
        Carta2.setText(nuevaBaraja.jugador1[1].número+" de "+nuevaBaraja.jugador1[1].palo);
        Carta3.setText(nuevaBaraja.jugador1[2].número+" de "+nuevaBaraja.jugador1[2].palo);
        Carta4.setText(nuevaBaraja.jugador1[3].número+" de "+nuevaBaraja.jugador1[3].palo);
        Carta5.setText(nuevaBaraja.jugador1[4].número+" de "+nuevaBaraja.jugador1[4].palo);
        Carta6.setText(nuevaBaraja.jugador1[5].número+" de "+nuevaBaraja.jugador1[5].palo);
        
        File miArchivo=new File("carta.jpg");
        
        try{
            BufferedImage miImagen=ImageIO.read(miArchivo);
            ImageIcon miIcono=new ImageIcon(miImagen);
            Prueba.setIcon(miIcono);
        }
        catch(IOException miExcepción){
            Prueba.setText("ups");
        }
    }//GEN-LAST:event_repartirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarCartas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carta1;
    private javax.swing.JLabel Carta2;
    private javax.swing.JLabel Carta3;
    private javax.swing.JLabel Carta4;
    private javax.swing.JLabel Carta5;
    private javax.swing.JLabel Carta6;
    private javax.swing.JLabel Prueba;
    private javax.swing.JMenu barajar;
    private javax.swing.JMenu crearBaraja;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu repartir;
    // End of variables declaration//GEN-END:variables
}
