/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cards;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiantes
 */
public class MostrarCartas extends javax.swing.JFrame {

    /**
     * Creates new form MostrarCartas
     */
    
    javax.swing.JLabel espacio[]=new javax.swing.JLabel[6];
    Baraja nuevaBaraja=new Baraja();
    
    public MostrarCartas() {
        initComponents();
        for(int i=0;i<6;i++){
            espacio[i]=new javax.swing.JLabel();
            if(i<3){
                espacio[i].setBounds(230*i,0,225,315); 
            }
            else{
                espacio[i].setBounds(230*(i-3),320,225,315); 
            }
            add(espacio[i]); 
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prueba = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        crearBaraja = new javax.swing.JMenu();
        barajar = new javax.swing.JMenu();
        repartir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crearBaraja.setText("Crear Baraja");
        crearBaraja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearBarajaMouseClicked(evt);
            }
        });
        jMenuBar1.add(crearBaraja);

        barajar.setText("Barajar");
        barajar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barajarMouseClicked(evt);
            }
        });
        jMenuBar1.add(barajar);

        repartir.setText("Repartir");
        repartir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                repartirMouseClicked(evt);
            }
        });
        jMenuBar1.add(repartir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(Prueba)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(Prueba)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearBarajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBarajaMouseClicked
        nuevaBaraja.crearBaraja();
    }//GEN-LAST:event_crearBarajaMouseClicked

    private void barajarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barajarMouseClicked
        if (nuevaBaraja.baraja[0] instanceof Carta) {
            nuevaBaraja.barajar();
        }else {
            JOptionPane.showMessageDialog(this, "Cree primero la baraja, caramba");
        }
    }//GEN-LAST:event_barajarMouseClicked

    private void repartirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repartirMouseClicked
        nuevaBaraja.repartir(6);
        
        File miArchivo=new File("baraja_1.jpg");
        if (nuevaBaraja.baraja[0] instanceof Carta) {
            for(int i=0;i<6;i++){
                try {
                    BufferedImage miImagen = ImageIO.read(miArchivo);
                    BufferedImage recorte;
                    recorte = miImagen.getSubimage(225 * (nuevaBaraja.jugador1[i].posición % 13), 315 * (nuevaBaraja.jugador1[i].posición / 13), 225, 315);
                    ImageIcon fin=new ImageIcon(recorte);
                    espacio[i].setIcon(fin);
                } catch (IOException ex) {
                    Logger.getLogger(MostrarCartas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Cree primero la baraja, caramba");
        }
        
    }//GEN-LAST:event_repartirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarCartas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Prueba;
    private javax.swing.JMenu barajar;
    private javax.swing.JMenu crearBaraja;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu repartir;
    // End of variables declaration//GEN-END:variables
}
