/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cards;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Estudiantes
 */
public class MostrarCartas extends javax.swing.JFrame {

    /**
     * Creates new form MostrarCartas
     */
    
    javax.swing.JLabel espacio[]=new javax.swing.JLabel[6];
    Baraja nuevaBaraja=new Baraja();
    
    public MostrarCartas() {
        initComponents();
        for(int i=0;i<6;i++){
            espacio[i]=new javax.swing.JLabel();
            if(i<3){
                espacio[i].setBounds(115*i,0,110,154); 
            }
            else{
                espacio[i].setBounds(115*(i-3),159,110,154); 
            }
            add(espacio[i]); 
        }
        barajar.disable();
        repartir.disable();
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prueba = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        crearBaraja = new javax.swing.JMenu();
        barajar = new javax.swing.JMenu();
        repartir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crearBaraja.setText("Crear Baraja");
        crearBaraja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearBarajaMouseClicked(evt);
            }
        });
        jMenuBar1.add(crearBaraja);

        barajar.setText("Barajar");
        barajar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barajarMouseClicked(evt);
            }
        });
        jMenuBar1.add(barajar);

        repartir.setText("Repartir");
        repartir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                repartirMouseClicked(evt);
            }
        });
        jMenuBar1.add(repartir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(Prueba)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(Prueba)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearBarajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBarajaMouseClicked
        nuevaBaraja.crearBaraja();
        barajar.enable();
        repartir.enable();
    }//GEN-LAST:event_crearBarajaMouseClicked

    private void barajarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barajarMouseClicked
        nuevaBaraja.barajar();
    }//GEN-LAST:event_barajarMouseClicked

    private void repartirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_repartirMouseClicked
        nuevaBaraja.repartir(6);
        
        File miArchivo=new File("carta.jpg");
        BufferedImage miImagen = null;
        try {
            miImagen = ImageIO.read(miArchivo);
        } catch (IOException ex) {
            Logger.getLogger(MostrarCartas.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon miIcono=new ImageIcon(miImagen);
        for(int i=0;i<6;i++){
            Image conversión = miIcono.getImage();
            Image tamaño = conversión.getScaledInstance(110, 154, Image.SCALE_SMOOTH);
            ImageIcon fin = new ImageIcon(tamaño);
            espacio[i].setIcon(fin);
        }
        
    }//GEN-LAST:event_repartirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarCartas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Prueba;
    private javax.swing.JMenu barajar;
    private javax.swing.JMenu crearBaraja;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu repartir;
    // End of variables declaration//GEN-END:variables
}
